name: build and push test-data-api

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.SECRET }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image and push to github
      run: docker build . --file src/iplink_src/Dockerfile --tag test-data-api:latest
    - name: Tag image
      run: docker image tag iplink:latest ghcr.io/backchristoffer/test-data-api:latest
    - name: Push image to github
      run: docker image push ghcr.io/backchristoffer/test-data-api:latest
